# よく使用するイメージの明示的マッピング
[[short-name]]
name = "rust"
value = "docker.io/library/rust"

[[short-name]]
name = "ubuntu"
value = "docker.io/library/ubuntu"

[[short-name]]
name = "debian"
value = "docker.io/library/debian"
