# -*- conf -*-

[main]
font=Noto Sans Mono CJK JP:size=8
dpi-aware=yes
pad = 6x4
term = foot

initial-window-size-chars=100x30

[scrollback]
lines = 10000

[cursor]
style = beam
blink = no

[key-bindings]
#copy-clipboard=Control+Shift+c
#paste-clipboard=Control+Shift+v
